
version: '3.8'

services:
  nifi:
    image: apache/nifi:1.28.0
    container_name: nifi
    ports:
      - '8080:8080'
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - nifi_data:/opt/nifi/nifi-current/logs

volumes:
  nifi_data:
